name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    uses: visciang/gha-elixir-workflow/.github/workflows/elixir.yml@v1
    with:
      image: hexpm/elixir:1.17.3-erlang-27.1-debian-bookworm-20240904
      tests: false
      build-docs: false
    secrets: inherit

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: gigalixir deploy
        run: |
          git remote add gigalixir https://${{ secrets.GIGALIXIR_EMAIL }}:${{ secrets.GIGALIXIR_API_KEY }}@git.gigalixir.com/${{ secrets.GIGALIXIR_APP_NAME }}.git
          git push -f gigalixir HEAD:refs/heads/master
